default: &default
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV['TESTAPP_USERNAME'] %>
  password: <%= ENV['TESTAPP_PASSWD'] %>

development:
  <<: *default
  database: testapp_dev

test:
  <<: *default
  database: testapp_test

production:
  host: <%= ENV['TESTAPP_HOST'] %>
  database: <%= ENV['TESTAPP_NAME'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV['TESTAPP_USERNAME'] %>
  password: <%= ENV['TESTAPP_PASSWORD'] %>
