# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9db544586c3bd483e1fe23c482781f2438bb271dd8d0f4b4edf0d4e774559a2cf96abe4531b781924913cf1e4907a14a245ec26ffaeac740b1256d4edd512d99

test:
  secret_key_base: b09c0ada9b4d7796fac4bb6e9809a75e6e8126e1af9bbed74c27533e0257f8dd07afa5807a580f045c587d5c281e5043a45ef15f66136380c8c5285ff9ec317c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
